---
title: "git_00"
author: "Tanya Craig"
date: "Fall 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

All in the golden afternoon
Full leisurely we glide;
For both our oars, with little skill,
By little arms are plied,
While little hands make vain pretence
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,
Some say in ice.
From what I’ve tasted of desire
I hold with those who favor fire.
But if it had to perish twice,

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,
      Shining with all his might:
He did his very best to make
      The billows smooth and bright —
And this was odd, because it was
      The middle of the night.

The moon was shining sulkily,
      Because she thought the sun
Had got no business to be there
      After the day was done —
"It's very rude of him," she said,
      "To come and spoil the fun."
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

After the 1916 Film

By Karisma Price
The Realization of a Negro’s Ambition requires melatonin & the soft dying body of a monkey face orchid.

The brilliant strangeness of watching everyone not you grow comfortable with themselves.

Trying to rehabilitate one or multiple racists.

Learning death does not fear you.

I am afraid of stars. The sky is a womb that allows for reentry.

Can you teach me how to rest? I know there are different avenues to happy but I still choose this one.

I’ve had panic attacks since I was five.

Everything you fear keeps you alive.

I am not safe inside the vehicle nor when I reach the tenor. Neglect, a different type of death. I mean here I am in the center of my body leaning left over exhausting myself.

I am a life skill. I am a body who loves the mercy of movement.

Tell me what to do specifically. I’d like some guidance.

I scare away all the punctuation

I am a sentence that is not allowed to end